  seleniumhub:
    image: selenium/hub
    ports:
       - 4446:4444

  firefoxnode:
    image: selenium/node-firefox-debug
    ports:
      - 5900

    links:
      - seleniumhub:hub

  chromenode:
    image: selenium/node-chrome-debug
    ports:
      - 5900
    links:
      - seleniumhub:hub

  firefox3node:
    image: selenium/node-firefox-debug:3.4.0-bismuth
    ports:
      - 5900
    links:
      - seleniumhub:hub